spring:
    application:
        name: eureka-register
eureka:
    client:
        fetchRegistry: false #eureka本身无需从注册中心获取服务器
        registerWithEureka: false #eureka本来就是注册中心，所以无需去注册中心注册，设为false
        serviceUrl:
            defalutZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: 127.0.0.1
server:
    port: 2222